apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: roboshop
data:
  RABBITMQ_DEFAULT_USER: roboshop
  RABBITMQ_DEFAULT_PASS: roboshop123
---
apiVersion: v1  #headless service
kind: Service
metadata:
  name: rabbitmq-headless-service
  namespace: roboshop
spec:
  # This makes the service "headless"
  clusterIP: None
  selector:
    project: roboshop
    tier: db
    component: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: rabbitmq # has to match .spec.template.metadata.labels
  serviceName: "rabbitmq-headless-service"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: rabbitmq # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: rabbitmq
        image: saithota9/rabbitmq:1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "15m"
            memory: "128Mi"
          limits:
            cpu: "75m"
            memory: "256Mi"
        # readinessProbe:
        #   tcpSocket:
        #     port: 5672
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 5672
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        envFrom:
         - configMapRef:
             name: rabbitmq
        volumeMounts:
        - name: rabbitmq-volume
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: my-ebs-sc
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq 
spec:
  selector:
    project: roboshop
    tier: db
    component: rabbitmq 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
