apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  MYSQL_ROOT_PASSWORD: "RoboShop@1"
---
apiVersion: v1  #headless service
kind: Service
metadata:
  name: mysql-headless-service
  namespace: roboshop
spec:
  # This makes the service "headless"
  clusterIP: None
  selector:
    project: roboshop
    tier: db
    component: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: mysql # has to match .spec.template.metadata.labels
  serviceName: "mysql-headless-service"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mysql # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
       - name: mysql
         image: saithota9/mysql:1.0.0
         imagePullPolicy: Always
         resources:
           requests:
             cpu: "100m"
             memory: "550Mi"
           limits:
             cpu: "300m"
             memory: "800Mi"
        #  startupProbe:
        #    tcpSocket:
        #      port: 3306
        #    failureThreshold: 60
        #    periodSeconds: 5
        #  readinessProbe:
        #    tcpSocket:
        #      port: 3306
        #    initialDelaySeconds: 120
        #    periodSeconds: 5
        #  livenessProbe:
        #    tcpSocket:
        #      port: 3306
        #    initialDelaySeconds: 120
        #    periodSeconds: 10
         envFrom:
           - configMapRef:
              name: mysql
         volumeMounts:
          - name: mysql-volume
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: my-ebs-sc
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql 
spec:
  selector:
    project: roboshop
    tier: db
    component: mysql 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
