apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: catalogue
  replicas: 1
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: catalogue   
    spec:
      containers:
        - name: catalogue
          image: saithota9/catalogue:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "55m"
              memory: "40Mi"
            limits:
              cpu: "100m"
              memory: "170Mi"
          readinessProbe:
            # httpGet:
            #   path: /health
            #   port: 8080
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            # httpGet:
            #   path: /health
            #   port: 8080
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: catalogue
      affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
               - matchExpressions:
                   - key: tier
                     operator: In
                     values:
                       - backend
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue 
spec:
  selector:
    project: roboshop
    tier: backend
    component: catalogue 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080